[package]
name                 = "astro2tsx"
version              = "0.1.0"
authors.workspace    = true
edition.workspace    = true
license.workspace    = true
repository.workspace = true
rust-version.workspace = true
publish              = false
description          = "Converts .astro files to .tsx for tsserver intellisense, using Biome's HTML CST"

[lib]
crate-type = ["cdylib", "lib"]
test       = true
doctest    = false

[dependencies]
biome_html_parser = { git = "https://github.com/Princesseuh/biome", rev = "2532865deaf49db5ecee53281a59ee01e95174ac" }
biome_html_syntax = { git = "https://github.com/Princesseuh/biome", rev = "2532865deaf49db5ecee53281a59ee01e95174ac" }
biome_js_parser = { git = "https://github.com/Princesseuh/biome", rev = "2532865deaf49db5ecee53281a59ee01e95174ac" }
biome_js_syntax = { git = "https://github.com/Princesseuh/biome", rev = "2532865deaf49db5ecee53281a59ee01e95174ac" }
biome_languages = { git = "https://github.com/Princesseuh/biome", rev = "2532865deaf49db5ecee53281a59ee01e95174ac" }
biome_rowan = { git = "https://github.com/Princesseuh/biome", rev = "2532865deaf49db5ecee53281a59ee01e95174ac" }

napi        = { workspace = true }
napi-derive = { workspace = true }
serde       = { version = "1", features = ["derive"] }
serde_json  = "1"

[dev-dependencies]
insta         = { workspace = true, features = ["glob"] }
oxc_sourcemap = { workspace = true }

[build-dependencies]
napi-build = { workspace = true }
