/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Convert an Astro source file to TSX for tsserver intellisense.
 *
 * The conversion is error-tolerant: malformed input produces a
 * best-effort TSX output rather than throwing, and `hasParseErrors` is
 * set to `true` when the parser surfaced one or more diagnostics.
 */
export declare function convertToTsx(source: string, options?: ConvertToTsxOptions | undefined | null): ConvertToTsxResult

export interface ConvertToTsxOptions {
  /**
   * Filename used to derive the default-exported component identifier
   * (e.g. `MyPage.astro` produces `MyPage__AstroComponent_`). Optional.
   */
  filename?: string
}

export interface ConvertToTsxResult {
  code: string
  mappings: Array<Mapping>
  frontmatter: GeneratedRange
  body: GeneratedRange
  scripts: Array<ExtractedTag>
  styles: Array<ExtractedTag>
  hasParseErrors: boolean
}

export interface ExtractedTag {
  range: GeneratedRange
  kind: ExtractedTagKind
  content: string
  lang?: string
}

export declare const enum ExtractedTagKind {
  Script = 'Script',
  Style = 'Style',
  StyleAttribute = 'StyleAttribute',
  EventAttribute = 'EventAttribute'
}

/** Byte range inside the generated TSX. */
export interface GeneratedRange {
  start: number
  end: number
}

/** Per-byte source-position mapping between the emitted TSX and the source. */
export interface Mapping {
  /** Byte offset into the generated TSX. */
  generated: number
  /**
   * Byte offset into the original `.astro` source. `None` for synthetic
   * content (e.g. the `<Fragment>` wrapping or the prefix comment).
   */
  original?: number
}
