/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface AstroDiagnostic {
  message: string
  severity: DiagnosticSeverity
  position: Range
}

export declare const enum AstroFrontmatterStatus {
  DoesntExist = 'doesnt-exist',
  Open = 'open',
  Closed = 'closed'
}

/**
 * Convert an Astro source file to TSX for tsserver intellisense.
 *
 * The conversion is error-tolerant: malformed input produces a
 * best-effort TSX output rather than throwing, and `hasParseErrors` is
 * set to `true` when the parser surfaced one or more diagnostics.
 */
export declare function convertToTsx(source: string, options?: ConvertToTsxOptions | undefined | null): ConvertToTsxResult

export interface ConvertToTsxOptions {
  /**
   * Filename used to derive the default-exported component identifier
   * (e.g. `MyPage.astro` produces `MyPage__AstroComponent_`). Optional.
   */
  filename?: string
  /**
   * `false` skips building the map entirely, `"external"` returns it in
   * `map` without touching `code`, and `true` / `"inline"` (the default)
   * also appends a `//# sourceMappingURL=` comment.
   */
  sourcemap?: boolean | string
  /**
   * Appends unmapped `declare` statements resolving the `Fragment` and
   * `Astro` globals the TSX references but never declares. Off by default:
   * consumers that inject their own ambient types must not receive them.
   */
  ambientTypes?: boolean
}

export interface ConvertToTsxResult {
  code: string
  /**
   * Offsets into `code` where each mapped run starts, ascending. Positions
   * inside a run resolve as `sourceOffsets[i] + (offset -
   * generatedOffsets[i])` while within `lengths[i]` — the shape Volar
   * mappings use. Output outside every run is synthetic.
   */
  generatedOffsets: Uint32Array
  sourceOffsets: Uint32Array
  lengths: Uint32Array
  /** Range of the frontmatter section within `code`. */
  frontmatter: Range
  /** Range of the `<Fragment>` body within `code`. */
  body: Range
  /**
   * Source Map v3 JSON for `code`, with `sourcesContent` embedded. `None`
   * when the caller opted out with `sourcemap: false`.
   */
  map?: string
  frontmatterStatus: AstroFrontmatterStatus
  /** Range of the frontmatter in the original source, fences included. */
  frontmatterSource: Range
  scripts: Array<ExtractedScript>
  styles: Array<ExtractedStyle>
  diagnostics: Array<AstroDiagnostic>
  hasParseErrors: boolean
}

export declare const enum DiagnosticSeverity {
  Error = 1,
  Warning = 2,
  Information = 3,
  Hint = 4
}

export interface ExtractedScript {
  /** Range of `content` in the original source. */
  position: Range
  content: string
  type: ExtractedScriptType
}

/**
 * How a `<script>`'s contents should be treated. A bare `<script>` is
 * processed by Astro; anything else is inlined as written.
 */
export declare const enum ExtractedScriptType {
  ProcessedModule = 'processed-module',
  Module = 'module',
  Inline = 'inline',
  EventAttribute = 'event-attribute',
  Json = 'json',
  Raw = 'raw',
  Unknown = 'unknown'
}

export interface ExtractedStyle {
  /** Range of `content` in the original source. */
  position: Range
  content: string
  type: ExtractedStyleType
  /** `css`, `scss`, `less`, … taken from the `lang` attribute. */
  lang: string
}

export declare const enum ExtractedStyleType {
  Tag = 'tag',
  StyleAttribute = 'style-attribute'
}

export interface Range {
  start: number
  end: number
}
