//! Converts `.astro` source into TSX.
//!
//! The conversion is error-tolerant: even malformed input produces a
//! best-effort TSX output, since the underlying parser produces bogus nodes
//! rather than failing outright.

#![deny(clippy::use_self)]

mod expression;
mod frontmatter;
#[cfg(not(test))]
mod napi;
mod printer;
mod props;
mod render;
pub mod sourcemap;
mod utils;

use biome_html_parser::parse_html;
use biome_languages::HtmlFileSource;

pub use crate::sourcemap::{
    DEFAULT_SOURCE_NAME, ExtractedKind, ExtractedTag, GeneratedRange, Mapping, SourceMap,
    SourceMapMode,
};

#[derive(Clone, Debug, Default)]
pub struct ConvertOptions {
    /// Component identifier source, and `sources[0]` in the source map.
    pub filename: Option<String>,
    pub sourcemap: SourceMapMode,
}

/// `code` is always populated, whether or not the input parsed cleanly.
#[derive(Debug, Default)]
pub struct ConvertResult {
    pub code: String,
    /// `(generated_offset, original_offset)` pairs.
    pub mappings: Vec<Mapping>,
    /// Generated byte range covering the printed frontmatter section.
    pub frontmatter: GeneratedRange,
    /// Generated byte range covering the printed body section
    /// (`<Fragment>...</Fragment>`).
    pub body: GeneratedRange,
    /// Extracted `<script>` blocks plus event-handler attributes.
    pub scripts: Vec<ExtractedTag>,
    /// Extracted `<style>` blocks plus inline `style="..."` attributes.
    pub styles: Vec<ExtractedTag>,
    /// Conversion still runs to completion when this is `true`.
    pub has_parse_errors: bool,
}

impl ConvertResult {
    /// Encodes [`Self::mappings`] as a Source Map v3 document, embedding
    /// `source` as `sourcesContent` so the map stands alone.
    pub fn source_map(&self, source: &str, source_name: &str) -> SourceMap {
        sourcemap::encode(source, &self.code, &self.mappings, source_name)
    }
}

pub fn convert_to_tsx(source: &str, options: ConvertOptions) -> ConvertResult {
    let parse = parse_html(source, (&HtmlFileSource::astro()).into());
    let html_has_errors = parse.has_errors();
    let root = parse.tree();

    let mut printer = printer::Printer::new(source);
    render::render_root(&mut printer, root, &options);

    let mut result = ConvertResult {
        code: printer.output,
        mappings: printer.mappings,
        frontmatter: printer.frontmatter_range,
        body: printer.body_range,
        scripts: printer.scripts,
        styles: printer.styles,
        has_parse_errors: html_has_errors || printer.has_expression_errors,
    };

    if options.sourcemap == SourceMapMode::Inline {
        let source_name = options.filename.as_deref().unwrap_or(DEFAULT_SOURCE_NAME);
        let comment = sourcemap::to_inline_comment(&result.source_map(source, source_name));
        result.code.push('\n');
        result.code.push_str(&comment);
    }

    result
}
