//! Converts `.astro` source into TSX.
//!
//! The conversion is error-tolerant: even malformed input produces a
//! best-effort TSX output, since the underlying parser produces bogus nodes
//! rather than failing outright.

#![deny(clippy::use_self)]

mod expression;
#[cfg(not(test))]
mod napi;
mod printer;
mod props;
mod render;
#[cfg(test)]
mod test_utils;
mod types;
mod utf16;
mod utils;

use biome_html_parser::parse_html;
use biome_languages::HtmlFileSource;

pub use crate::types::{
    Diagnostic, DiagnosticSeverity, ExtractedKind, ExtractedScriptType, ExtractedTag,
    FrontmatterInfo, FrontmatterStatus, GeneratedRange, Mapping, SourceRange,
};

#[derive(Clone, Debug, Default)]
pub struct ConvertOptions {
    /// Component identifier source.
    pub filename: Option<String>,
    /// Appends `declare` statements resolving the `Fragment` and `Astro` globals.
    pub ambient_types: bool,
}

/// `code` is always populated, whether or not the input parsed cleanly.
#[derive(Debug, Default)]
pub struct ConvertResult {
    pub code: String,
    /// Run starts, ascending: each mapping holds until the next one, with
    /// generated and original offsets advancing in lockstep.
    pub mappings: Vec<Mapping>,
    /// Generated byte range covering the printed frontmatter section.
    pub frontmatter_range: GeneratedRange,
    /// Generated byte range covering the printed body section
    /// (`<Fragment>...</Fragment>`).
    pub body: GeneratedRange,
    /// Extracted `<script>` blocks plus event-handler attributes.
    pub scripts: Vec<ExtractedTag>,
    /// Extracted `<style>` blocks plus inline `style="..."` attributes.
    pub styles: Vec<ExtractedTag>,
    /// Conversion still runs to completion when this is `true`.
    pub has_parse_errors: bool,
    /// Parse diagnostics from the document and its expression bodies.
    pub diagnostics: Vec<Diagnostic>,
    pub frontmatter: FrontmatterInfo,
}

pub fn convert_to_tsx(source: &str, options: ConvertOptions) -> ConvertResult {
    let parse = parse_html(source, (&HtmlFileSource::astro()).into());
    let root = parse.tree();

    let mut printer = printer::Printer::new(source);
    render::render_root(&mut printer, root, &options);

    let mut diagnostics: Vec<Diagnostic> = parse
        .diagnostics()
        .iter()
        .filter_map(|diagnostic| {
            let source = match biome_diagnostics::Diagnostic::location(diagnostic).span {
                Some(span) => SourceRange::new(u32::from(span.start()), u32::from(span.end())),
                None => SourceRange::new(0, source.len() as u32),
            };
            if printer.suppressed_html_diagnostics.iter().any(|range| {
                if source.start == source.end {
                    range.start <= source.start && source.start <= range.end
                } else {
                    range.start < source.end && source.start < range.end
                }
            }) {
                return None;
            }
            Some(Diagnostic {
                message: diagnostic.message.to_string(),
                severity: DiagnosticSeverity::Error,
                source,
            })
        })
        .collect();
    let html_has_errors = !diagnostics.is_empty();
    diagnostics.extend(printer.diagnostics);
    diagnostics.sort_by_key(|diagnostic| (diagnostic.source.start, diagnostic.source.end));
    diagnostics.dedup();

    ConvertResult {
        code: printer.output,
        mappings: printer.mappings,
        frontmatter_range: printer.frontmatter_range,
        body: printer.body_range,
        scripts: printer.scripts,
        styles: printer.styles,
        has_parse_errors: html_has_errors || printer.has_embedded_parse_errors,
        diagnostics,
        frontmatter: printer.frontmatter_info,
    }
}

#[cfg(test)]
mod tests {
    use crate::test_utils::assert_mapped_runs_are_verbatim;
    use crate::{ConvertOptions, convert_to_tsx};

    const PREFIX: &str = "/* @jsxImportSource astro */\n\n";

    #[test]
    fn parser_errors_surface_but_do_not_block_emission() {
        let result = convert_to_tsx(
            "---\nconst items = [1];\n---\n{items.map(i => <div>{i}</div>)",
            ConvertOptions::default(),
        );
        assert!(result.has_parse_errors);
        assert!(result.code.starts_with(PREFIX));
    }

    #[test]
    fn diagnostics_carry_positions_pointing_at_the_problem() {
        let source = "<div>{x ==}</div>";
        let result = convert_to_tsx(source, ConvertOptions::default());
        assert!(!result.diagnostics.is_empty());
        for diagnostic in &result.diagnostics {
            assert!(!diagnostic.message.is_empty());
            assert!(
                diagnostic.source.end as usize <= source.len(),
                "{diagnostic:?} runs past the source"
            );
            assert!(diagnostic.source.start <= diagnostic.source.end);
        }
    }

    #[test]
    fn tolerates_line_separators() {
        for input in [
            "\u{2028}",
            "something\u{2029}something",
            "something\u{2028}\u{2029}",
            "\u{2028}\u{2029}\u{2028}",
        ] {
            let actual = convert_to_tsx(input, ConvertOptions::default()).code;
            assert!(
                actual.starts_with(PREFIX),
                "input {input:?} produced no usable output"
            );
        }
    }

    #[test]
    fn malformed_input_never_panics_in_the_parser() {
        for input in ["<div></{<//", "<a></", "</", "<//", "<div></{", "{<//}"] {
            let result = convert_to_tsx(input, ConvertOptions::default());
            assert!(result.code.starts_with(PREFIX), "no output for {input:?}");
        }
    }

    #[test]
    fn unclosed_elements_are_emitted_as_written_and_flagged() {
        for (input, expected) in [
            ("<div>hello", "<div>hello"),
            ("<Card>\n  <p>text</p>", "<Card>\n  <p>text</p>"),
            ("<p>one<p>two", "<p>one<p>two"),
            ("<>{1}<p>x</p>", "<>{1}<p>x</p>"),
            (
                "<table><tr><td>a<td>b</tr></table>",
                "<td>a<td>b</tr></table>",
            ),
            ("<div>x</div", "<div>x</div"),
            ("<>x", "<>x"),
            ("<img /", "<img /"),
        ] {
            let result = convert_to_tsx(input, ConvertOptions::default());
            assert!(
                result.code.contains(expected),
                "content lost for {input:?}:\n{}",
                result.code
            );
            assert!(
                !result.code.contains("</div>") || input.contains("</div>"),
                "a closing tag was synthesized for {input:?}:\n{}",
                result.code
            );
            assert!(result.has_parse_errors, "{input:?} must stay flagged");
            assert_mapped_runs_are_verbatim(input, &result, "unclosed as written");
        }

        let truncated = convert_to_tsx("<div>x</div", ConvertOptions::default());
        assert!(!truncated.code.contains("</div>"), "{}", truncated.code);
        let fragment = convert_to_tsx("<>x", ConvertOptions::default());
        assert!(!fragment.code.contains("</>"), "{}", fragment.code);
    }
}
