//! Node.js bindings for `astro2tsx`. Excluded from `cfg(test)` builds, where
//! napi-derive emits no registration and every item here looks dead.

use napi::bindgen_prelude::Uint32Array;
use napi_derive::napi;

use crate::{
    ConvertOptions, DEFAULT_SOURCE_NAME, ExtractedKind, SourceMapMode, convert_to_tsx as convert_rs,
};

/// Byte range inside the generated TSX.
#[napi(object)]
pub struct GeneratedRange {
    pub start: u32,
    pub end: u32,
}

#[napi(string_enum)]
pub enum ExtractedTagKind {
    Script,
    Style,
    StyleAttribute,
    EventAttribute,
}

#[napi(object)]
pub struct ExtractedTag {
    pub range: GeneratedRange,
    pub kind: ExtractedTagKind,
    pub content: String,
    pub lang: Option<String>,
}

#[napi(object)]
#[derive(Default)]
pub struct ConvertToTsxOptions {
    /// Filename used to derive the default-exported component identifier
    /// (e.g. `MyPage.astro` produces `MyPage__AstroComponent_`). Optional.
    pub filename: Option<String>,
    /// `"external"` omits the inline `//# sourceMappingURL=`; anything else appends it.
    pub sourcemap: Option<String>,
}

#[napi(object)]
pub struct ConvertToTsxResult {
    pub code: String,
    /// Byte offsets into `code` where each mapped run starts, ascending.
    /// Positions inside a run resolve as `sourceOffsets[i] + (offset -
    /// generatedOffsets[i])` while within `lengths[i]` — the shape Volar
    /// mappings use. Generated bytes outside every run are synthetic.
    pub generated_offsets: Uint32Array,
    pub source_offsets: Uint32Array,
    pub lengths: Uint32Array,
    /// Source Map v3 JSON for `code`, with `sourcesContent` embedded.
    pub map: String,
    pub frontmatter: GeneratedRange,
    pub body: GeneratedRange,
    pub scripts: Vec<ExtractedTag>,
    pub styles: Vec<ExtractedTag>,
    pub has_parse_errors: bool,
}

/// Convert an Astro source file to TSX for tsserver intellisense.
///
/// The conversion is error-tolerant: malformed input produces a
/// best-effort TSX output rather than throwing, and `hasParseErrors` is
/// set to `true` when the parser surfaced one or more diagnostics.
#[napi(js_name = "convertToTsx")]
pub fn convert_to_tsx(source: String, options: Option<ConvertToTsxOptions>) -> ConvertToTsxResult {
    let opts = options.unwrap_or_default();
    let source_name = opts
        .filename
        .clone()
        .unwrap_or_else(|| DEFAULT_SOURCE_NAME.to_string());
    let result = convert_rs(
        &source,
        ConvertOptions {
            filename: opts.filename,
            sourcemap: match opts.sourcemap.as_deref() {
                Some("external") => SourceMapMode::External,
                _ => SourceMapMode::Inline,
            },
        },
    );
    let map = result.source_map(&source, &source_name).to_json_string();

    let mut generated_offsets = Vec::new();
    let mut source_offsets = Vec::new();
    let mut lengths = Vec::new();
    for (index, mapping) in result.mappings.iter().enumerate() {
        let Some(original) = mapping.original else {
            continue;
        };
        let run_end = result
            .mappings
            .get(index + 1)
            .map(|next| next.generated)
            .unwrap_or(result.code.len() as u32);
        generated_offsets.push(mapping.generated);
        source_offsets.push(original);
        lengths.push(run_end - mapping.generated);
    }

    ConvertToTsxResult {
        code: result.code,
        map,
        generated_offsets: Uint32Array::new(generated_offsets),
        source_offsets: Uint32Array::new(source_offsets),
        lengths: Uint32Array::new(lengths),
        frontmatter: GeneratedRange {
            start: result.frontmatter.start,
            end: result.frontmatter.end,
        },
        body: GeneratedRange {
            start: result.body.start,
            end: result.body.end,
        },
        scripts: result
            .scripts
            .into_iter()
            .map(extracted_tag_to_napi)
            .collect(),
        styles: result
            .styles
            .into_iter()
            .map(extracted_tag_to_napi)
            .collect(),
        has_parse_errors: result.has_parse_errors,
    }
}

fn extracted_tag_to_napi(tag: crate::ExtractedTag) -> ExtractedTag {
    ExtractedTag {
        range: GeneratedRange {
            start: tag.range.start,
            end: tag.range.end,
        },
        kind: match tag.kind {
            ExtractedKind::Script => ExtractedTagKind::Script,
            ExtractedKind::Style => ExtractedTagKind::Style,
            ExtractedKind::StyleAttribute => ExtractedTagKind::StyleAttribute,
            ExtractedKind::EventAttribute => ExtractedTagKind::EventAttribute,
        },
        content: tag.content,
        lang: tag.lang,
    }
}
