name: Close Issues (needs repro)

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  close-issues:
    if: github.repository == 'withastro/compiler'
    runs-on: ubuntu-latest
    steps:
      - name: needs repro
        uses: actions-cool/issues-helper@1c9e803c80cc7fed000022d4c94f4b5bc2e90062 # v3.8.0
        with:
          actions: "close-issues"
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: "needs repro"
          inactive-day: 3
