name: Label issues
on:
  issues:
    types:
      - reopened
      - opened

jobs:
  label_issues:
    if: github.repository_owner == 'withastro'
    uses: withastro/automation/.github/workflows/issue-opened.yml@2946ab18ea547e22a48eb7f338caed3b99bcf52f # main
