name: Issue Labeled

on:
  issues:
    types: [labeled]

jobs:
  reply_labelled:
    if: github.repository_owner == 'withastro'
    uses: withastro/automation/.github/workflows/issue-labeled.yml@2946ab18ea547e22a48eb7f338caed3b99bcf52f # main
